"""
Django settings for TradieRMProject project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

import dotenv

dotenv.load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# =============================================================================
# SECURITY SETTINGS
# =============================================================================
# WARNING: keep the secret key used in production secret.
# WARNING: do not run with DEBUG = True in production.

SECRET_KEY = 'django-insecure-(%)shg&nu#_34w4f=750=)u-0o)j^!kpkl&_xo@#=a&98q%&ef'

DEBUG = True

ALLOWED_HOSTS = ['*']


# =============================================================================
# ENVIRONMENT VARIABLE LOADER
# =============================================================================
# Reads key=value pairs from a .env file in the project root and injects them
# into os.environ. This avoids hardcoding credentials in settings.py without
# requiring third-party packages such as python-decouple or python-dotenv.
#
# The .env file must be listed in .gitignore to prevent credential exposure.
# Lines beginning with '#' and blank lines are ignored.
# =============================================================================

def _load_env_file(env_path):
    """
    Parse a .env file and populate os.environ with its key-value pairs.

    Only keys that are not already present in os.environ are set, allowing
    actual system environment variables to take precedence over .env values.

    Args:
        env_path: pathlib.Path pointing to the .env file.
    """
    if not env_path.exists():
        return

    with open(env_path, encoding='utf-8') as fh:
        for line in fh:
            line = line.strip()

            # Skip blank lines and comments.
            if not line or line.startswith('#'):
                continue

            # Skip lines that do not contain an assignment operator.
            if '=' not in line:
                continue

            key, _, value = line.partition('=')
            key   = key.strip()
            value = value.strip()

            # Strip optional surrounding quotes from the value.
            if len(value) >= 2 and value[0] in ('"', "'") and value[-1] == value[0]:
                value = value[1:-1]

            # Do not override variables already set in the system environment.
            if key and key not in os.environ:
                os.environ[key] = value


_load_env_file(BASE_DIR / '.env')


# =============================================================================
# APPLICATION DEFINITION
# =============================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'tradiePrototype',
    'corsheaders',
    'django_extensions',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'TradieRMProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TradieRMProject.wsgi.application'


# =============================================================================
# DATABASE CONFIGURATION
# =============================================================================
# Connection parameters are read from environment variables so that no
# credentials are stored in source code.
#
# Required environment variables:
#   PGHOST, PGDATABASE, PGPORT, PGUSER, PGPASSWORD
# =============================================================================

DATABASES = {
    'default': {
        'ENGINE':   'django.db.backends.postgresql',
        'HOST':     os.getenv('PGHOST'),
        'NAME':     os.getenv('PGDATABASE'),
        'PORT':     os.getenv('PGPORT'),
        'USER':     os.getenv('PGUSER'),
        'PASSWORD': os.getenv('PGPASSWORD'),
    }
}


# =============================================================================
# PASSWORD VALIDATION
# =============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# =============================================================================
# INTERNATIONALISATION
# =============================================================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE     = 'UTC'
USE_I18N      = True
USE_TZ        = True


# =============================================================================
# STATIC FILES
# =============================================================================

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =============================================================================
# DJANGO REST FRAMEWORK
# =============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}


# =============================================================================
# EMAIL CONFIGURATION -- Gmail SMTP
# =============================================================================
# Transactional email is delivered via Gmail's SMTP relay service.
# This configuration is suitable for development and low-volume production use.
#
# Prerequisites:
#   1. Google account must have 2-Step Verification enabled.
#   2. An App Password must be generated (NOT your regular Gmail password).
#
# App Password setup:
#   Google Account -> Security -> 2-Step Verification -> App Passwords
#   -> App name: TradieRM -> Copy the 16-character password generated.
#
# Environment variable setup (.env file in project root):
#   EMAIL_HOST_USER     = your_gmail_address@gmail.com
#   EMAIL_HOST_PASSWORD = xxxx xxxx xxxx xxxx
#   DEFAULT_FROM_EMAIL  = your_gmail_address@gmail.com
#
# Sending limit: 500 emails/day -- sufficient for capstone demonstration.
# Ensure .env is listed in .gitignore -- never commit credentials.
# =============================================================================

EMAIL_BACKEND       = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST          = 'smtp.gmail.com'
EMAIL_PORT          = 587
EMAIL_USE_TLS       = True
EMAIL_HOST_USER     = os.environ.get('EMAIL_HOST_USER',     '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL  = os.environ.get('DEFAULT_FROM_EMAIL',  '')


# =============================================================================
# CORS CONFIGURATION
# =============================================================================
# CORS_ALLOWED_ORIGINS is built from a hardcoded local-development whitelist
# plus any additional origins supplied via the CORS_ALLOWED_ORIGINS environment
# variable as a comma-separated list.
#
# This allows new deployment URLs (Vercel, staging, etc.) to be added without
# modifying source code -- set the variable in the hosting platform's
# environment panel instead.
#
# Example .env / environment variable entry:
#   CORS_ALLOWED_ORIGINS=https://tradierm-ui-test.vercel.app
# =============================================================================

_cors_env   = os.environ.get('CORS_ALLOWED_ORIGINS', '')
_cors_extra = [origin.strip() for origin in _cors_env.split(',') if origin.strip()]

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:3001',
    'http://127.0.0.1:3001',
] + _cors_extra


# =============================================================================
# SITE BASE URL
# =============================================================================
# Used by UC4 to construct the signed booking form link embedded in the
# customer email. Must point to the frontend origin where /booking/submit
# is served.
#
# Local development: http://localhost:3000  (default fallback)
# Cloud deployment:  set SITE_BASE_URL in the backend hosting platform's
#                    environment panel, e.g.:
#                      SITE_BASE_URL=https://tradierm-ui-test.vercel.app
# =============================================================================

SITE_BASE_URL = os.environ.get('SITE_BASE_URL', 'http://localhost:3000')


# =============================================================================
# THIRD-PARTY SERVICE CONFIGURATION
# =============================================================================

# OpenRouteService API key used for road-distance calculations (UC17).
ORS_API_KEY = os.environ.get('ORS_API_KEY', 'your_openrouteservice_api_key')

# Recipient address for administrator alert emails.
ADMIN_NOTIFICATION_EMAIL = os.environ.get('ADMIN_NOTIFICATION_EMAIL', 'doxdoxdox9@gmail.com')

# Company contact details sent to clients when webhook validation fails (UC1, Step 3a.3).
COMPANY_CONTACT_PHONE = os.environ.get('COMPANY_CONTACT_PHONE', '+61 3 9000 0000')
COMPANY_CONTACT_EMAIL = os.environ.get('COMPANY_CONTACT_EMAIL', 'info@tradierm.com')


# =============================================================================
# INVOICE CONFIGURATION
# =============================================================================

# Percentage added to the labour + parts subtotal as a service charge.
INVOICE_SERVICE_CHARGE_PERCENTAGE = float(os.environ.get('INVOICE_SERVICE_CHARGE_PERCENTAGE', '10.00'))

# Per-kilometre rate applied to road distance when calculating distance cost.
INVOICE_DISTANCE_RATE = float(os.environ.get('INVOICE_DISTANCE_RATE', '1.50'))


# =============================================================================
# AI RESPONSE SETTINGS (BR4/BR5 -- descoped from active implementation)
# =============================================================================
# Uses Ollama -- free, local, no API key required.
# Install: https://ollama.com/download
# Then run: ollama pull llama3.2 && ollama serve

OLLAMA_BASE_URL = os.environ.get('OLLAMA_BASE_URL', 'http://localhost:11434')
OLLAMA_MODEL    = os.environ.get('OLLAMA_MODEL',    'llama3.2')