"""
Django settings for TradieRMProject project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

"""
Django settings for CRM Backend (single-app version)
Database: SQLite (local)
"""

from pathlib import Path
import os
# import dot
import dotenv


dotenv.load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(%)shg&nu#_34w4f=750=)u-0o)j^!kpkl&_xo@#=a&98q%&ef'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# =============================================================================
# ENVIRONMENT VARIABLE LOADER
# =============================================================================
# Reads key=value pairs from a .env file in the project root and injects them
# into os.environ. This avoids hardcoding credentials in settings.py without
# requiring third-party packages such as python-decouple or python-dotenv.
#
# The .env file must be listed in .gitignore to prevent credential exposure.
# Lines beginning with '#' and blank lines are ignored.
# =============================================================================

def _load_env_file(env_path):
    """
    Parse a .env file and populate os.environ with its key-value pairs.

    Only keys that are not already present in os.environ are set, allowing
    actual system environment variables to take precedence over .env values.

    Args:
        env_path: pathlib.Path pointing to the .env file.
    """
    if not env_path.exists():
        return

    with open(env_path, encoding='utf-8') as fh:
        for line in fh:
            line = line.strip()

            # Skip blank lines and comments.
            if not line or line.startswith('#'):
                continue

            # Skip lines that do not contain an assignment operator.
            if '=' not in line:
                continue

            key, _, value = line.partition('=')
            key   = key.strip()
            value = value.strip()

            # Strip optional surrounding quotes from the value.
            if len(value) >= 2 and value[0] in ('"', "'") and value[-1] == value[0]:
                value = value[1:-1]

            # Do not override variables already set in the system environment.
            if key and key not in os.environ:
                os.environ[key] = value


_load_env_file(BASE_DIR / '.env')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'tradiePrototype',
    'corsheaders',
    'django_extensions',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'TradieRMProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TradieRMProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': os.getenv('PGHOST'),
        'NAME': os.getenv('PGDATABASE'),
        'PORT': os.getenv('PGPORT'),
        'USER': os.getenv('PGUSER'),
        'PASSWORD': os.getenv('PGPASSWORD'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Django REST Framework ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# --- AI Response Settings (BR4/BR5) ---
# Uses Ollama — free, local, no API key required.
# Install: https://ollama.com/download
# Then run: ollama pull llama3.2 && ollama serve
OLLAMA_BASE_URL = 'http://localhost:11434'
OLLAMA_MODEL = 'llama3.2'  # swap for mistral, gemma2, phi3, etc.

# # --- Email / Webhook confirmation (BR3) ---
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # swap for SMTP in production
# DEFAULT_FROM_EMAIL = 'noreply@example.com'

# =============================================================================
# EMAIL CONFIGURATION -- Gmail SMTP
# =============================================================================
# Transactional email is delivered via Gmail's SMTP relay service.
# This configuration is suitable for development and low-volume production use.
#
# Prerequisites:
#   1. Google account must have 2-Step Verification enabled.
#   2. An App Password must be generated (NOT your regular Gmail password).
#
# App Password setup:
#   Google Account -> Security -> 2-Step Verification -> App Passwords
#   -> App name: TradieRM -> Copy the 16-character password generated.
#
# Environment variable setup (.env file in project root):
#   EMAIL_HOST_USER     = your_gmail_address@gmail.com
#   EMAIL_HOST_PASSWORD = xxxx xxxx xxxx xxxx
#   DEFAULT_FROM_EMAIL  = your_gmail_address@gmail.com
#
# Sending limit: 500 emails/day -- sufficient for capstone demonstration.
# Ensure .env is listed in .gitignore -- never commit credentials.
# =============================================================================

EMAIL_BACKEND       = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST          = 'smtp.gmail.com'
EMAIL_PORT          = 587
EMAIL_USE_TLS       = True
EMAIL_HOST_USER     = os.environ.get('EMAIL_HOST_USER',     '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL  = os.environ.get('DEFAULT_FROM_EMAIL',  '')

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:3001',
    'http://127.0.0.1:3001',
    'https://your-frontend.vercel.app',
]

ORS_API_KEY = 'your_openrouteservice_api_key'
ADMIN_NOTIFICATION_EMAIL = 'doxdoxdox9@gmail.com'
SITE_BASE_URL = 'http://localhost:3000'

# Company contact details sent to clients when webhook validation fails (UC1, Step 3a.3).
COMPANY_CONTACT_PHONE = '+61 3 9000 0000'
COMPANY_CONTACT_EMAIL = 'info@tradierm.com'

INVOICE_SERVICE_CHARGE_PERCENTAGE = 10.00
INVOICE_DISTANCE_RATE             = 1.50