# Generated by Django 6.0.3 on 2026-04-02 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradiePrototype', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock')], default='in_stock', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Inventory',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date_generated']},
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='created_at',
            new_name='date_generated',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='grand_total',
            new_name='distance',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='labour_total',
            new_name='distance_cost',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='parts_total',
            new_name='distance_rate',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_address',
            new_name='admin_feedback',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='description',
            new_name='client_message',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='title',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='issued_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='labour_hours',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='labour_rate',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_instructions',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='job',
            name='scheduled_end',
        ),
        migrations.RemoveField(
            model_name='job',
            name='scheduled_start',
        ),
        migrations.RemoveField(
            model_name='job',
            name='travel_time_minutes',
        ),
        migrations.AddField(
            model_name='invoice',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='hours_taken',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='labour_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='markup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='parts_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='tradiePrototype.technician'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='job',
            name='client_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='tradiePrototype.clientrequest'),
        ),
        migrations.AddField(
            model_name='job',
            name='technician_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='technician',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='technician',
            name='skill',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Unprocessed'), ('processed', 'Processed')], default='unprocessed', max_length=15),
        ),
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual (Admin)'), ('webhook', 'Webhook / API')], default='manual', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('allocated', 'Allocated'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='pending', max_length=15),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_address', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('booking_token', models.CharField(blank=True, db_index=True, max_length=255)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='tradiePrototype.customer')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tradiePrototype.job')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='tradiePrototype.technician')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.AddField(
            model_name='scheduleblock',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_blocks', to='tradiePrototype.booking'),
        ),
        migrations.CreateModel(
            name='JobInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.IntegerField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_inventory', to='tradiePrototype.inventory')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_inventory', to='tradiePrototype.job')),
            ],
            options={
                'verbose_name_plural': 'Job Inventory',
                'unique_together': {('job', 'inventory')},
            },
        ),
        migrations.DeleteModel(
            name='JobPart',
        ),
    ]
