# Generated by Django 6.0.3 on 2026-04-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradiePrototype', '0003_inventory_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
