# Generated by Django 6.0.3 on 2026-04-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradiePrototype', '0006_rename_markup_invoice_service_charge_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='email_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.AddField(
            model_name='customer',
            name='physical_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
