# Generated by Django 6.0.3 on 2026-04-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradiePrototype', '0007_rename_email_customer_email_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email_address',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
