# Generated by Django 6.0.3 on 2026-04-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradiePrototype', '0008_alter_customer_email_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientrequest',
            options={'ordering': ['-date_received']},
        ),
        migrations.RenameField(
            model_name='clientrequest',
            old_name='created_at',
            new_name='date_received',
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='message',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='email',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='home_address',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='phone',
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='client_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='email_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='job',
            name='job_title',
            field=models.CharField(default='Untitled Job', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technician',
            name='email_address',
            field=models.CharField(default='Untitled Job', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technician',
            name='physical_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='technician',
            name='role',
            field=models.CharField(choices=[('technician', 'Technician')], default='technician', max_length=15),
        ),
        migrations.AddField(
            model_name='technician',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='technician',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='technician',
            name='username',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('inactive', 'Inactive')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='technician',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='technician',
            name='skill',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
