# Generated by Django 6.0.3 on 2026-04-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradiePrototype', '0010_alter_booking_date_alter_booking_physical_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='snapshot_customer_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='snapshot_customer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='snapshot_customer_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
