# Generated by Django 6.0.3 on 2026-04-24 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradiePrototype', '0011_invoice_customer_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='username',
        ),
    ]
